language: ruby
before_install:
  - rvm @global do gem uninstall bundler --all --executables
  - gem uninstall bundler --all --executables
  - gem install bundler -v '< 1.7.0'
script: bundle exec rake build
rvm:
- 2.1.5
- 2.0.0
